In [3]:
import pandas as pd
import numpy as np
from dateutil import parser
import seaborn as sns
# import plotly.express as px
import matplotlib.pyplot as plt

In [5]:
#Loading the csv file
df = pd.read_csv("data/jiji_housing_raw.csv")

df.head()

,title,region,region_name,region_parent_name,price,bedrooms,bathrooms,property_size,furnishing,is_boost
0,2bdrm Apartment in Lekki Phase 1 for sale,"Lekki, Lekki Phase 1",Lekki Phase 1,Lekki,"₦ 350,000,000",2,3,150,Semi-Furnished,enterprise
1,5bdrm Duplex in Wuse 2 for sale,"Abuja (FCT), Wuse 2",Wuse 2,Abuja (FCT),"₦ 1,300,000,000",5,6,1200,Unfurnished,diamond
2,4bdrm Duplex in Sangotedo for sale,"Ajah, Sangotedo",Sangotedo,Ajah,"₦ 180,000,000",4,4,300,Unfurnished,enterprise
3,4bdrm Duplex in Gaduwa for sale,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),"₦ 350,000,000",4,4,600,Semi-Furnished,vip
4,4bdrm Duplex in Gbagada Lagos for sale,"Gbagada, Oworonshoki / Gbagada",Oworonshoki / Gbagada,Gbagada,"₦ 300,000,000",4,5,150,Semi-Furnished,enterprise

In [8]:
#Missing value check

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               20 non-null     str
 1   region              20 non-null     str
 2   region_name         20 non-null     str
 3   region_parent_name  20 non-null     str
 4   price               20 non-null     str
 5   bedrooms            20 non-null     int64
 6   bathrooms           20 non-null     int64
 7   property_size       20 non-null     int64
 8   furnishing          20 non-null     str
 9   is_boost            20 non-null     str
dtypes: int64(3), str(7)
memory usage: 3.8 KB

In [11]:
df.columns = df.columns.str.title()
df.columns

Index(['Title', 'Region', 'Region_Name', 'Region_Parent_Name', 'Price',
       'Bedrooms', 'Bathrooms', 'Property_Size', 'Furnishing', 'Is_Boost'],
      dtype='str')

In [13]:
#Clean price

df['Price'] = (
    df['Price']
    .astype(str)
    .replace(r"[₦,]", "", regex=True)
    .astype(float)
)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               20 non-null     str
 1   Region              20 non-null     str
 2   Region_Name         20 non-null     str
 3   Region_Parent_Name  20 non-null     str
 4   Price               20 non-null     float64
 5   Bedrooms            20 non-null     int64
 6   Bathrooms           20 non-null     int64
 7   Property_Size       20 non-null     int64
 8   Furnishing          20 non-null     str
 9   Is_Boost            20 non-null     str
dtypes: float64(1), int64(3), str(6)
memory usage: 3.5 KB

In [15]:
#Dealing with Outliers

Q1 = df['Price'].quantile(0.25)
Q3 = df['Price'].quantile(0.75)

IQR = Q3 - Q1

#Finding the Lower and upper bounds
lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR

outliers = (df['Price'] < lower_bound) | (df['Price'] > upper_bound)

print('Outliers:', outliers.sum())

Outliers: 1

In [17]:
#Excluding Outliers from dataframe using ""

lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR

new_df = df[
    (df['Price'] > lower_bound) & (df['Price'] < upper_bound)
]

new_df.info()

<class 'pandas.DataFrame'>
Index: 19 entries, 0 to 19
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               19 non-null     str
 1   Region              19 non-null     str
 2   Region_Name         19 non-null     str
 3   Region_Parent_Name  19 non-null     str
 4   Price               19 non-null     float64
 5   Bedrooms            19 non-null     int64
 6   Bathrooms           19 non-null     int64
 7   Property_Size       19 non-null     int64
 8   Furnishing          19 non-null     str
 9   Is_Boost            19 non-null     str
dtypes: float64(1), int64(3), str(6)
memory usage: 3.3 KB

In [20]:
#Convert furnishing type to consistent categories

new_df['Furnishing'] = new_df['Furnishing'].astype(str).str.title()

new_df.head()

,Title,Region,Region_Name,Region_Parent_Name,Price,Bedrooms,Bathrooms,Property_Size,Furnishing,Is_Boost
0,2bdrm Apartment in Lekki Phase 1 for sale,"Lekki, Lekki Phase 1",Lekki Phase 1,Lekki,3.500000e+08,2,3,150,Semi-Furnished,enterprise
1,5bdrm Duplex in Wuse 2 for sale,"Abuja (FCT), Wuse 2",Wuse 2,Abuja (FCT),1.300000e+09,5,6,1200,Unfurnished,diamond
2,4bdrm Duplex in Sangotedo for sale,"Ajah, Sangotedo",Sangotedo,Ajah,1.800000e+08,4,4,300,Unfurnished,enterprise
3,4bdrm Duplex in Gaduwa for sale,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),3.500000e+08,4,4,600,Semi-Furnished,vip
4,4bdrm Duplex in Gbagada Lagos for sale,"Gbagada, Oworonshoki / Gbagada",Oworonshoki / Gbagada,Gbagada,3.000000e+08,4,5,150,Semi-Furnished,enterprise

In [50]:

#Convert is_boost type to consistent categories

new_df['Is_Boost'] = new_df['Is_Boost'].astype(str).str.title()

new_df.head()

,Title,Region,Region_Name,Region_Parent_Name,Price,Bedrooms,Bathrooms,Property_Size,Furnishing,Is_Boost
0,2bdrm Apartment in Lekki Phase 1 for sale,"Lekki, Lekki Phase 1",Lekki Phase 1,Lekki,3.500000e+08,2,3,150,Semi-Furnished,Enterprise
1,5bdrm Duplex in Wuse 2 for sale,"Abuja (FCT), Wuse 2",Wuse 2,Abuja (FCT),1.300000e+09,5,6,1200,Unfurnished,Diamond
2,4bdrm Duplex in Sangotedo for sale,"Ajah, Sangotedo",Sangotedo,Ajah,1.800000e+08,4,4,300,Unfurnished,Enterprise
3,4bdrm Duplex in Gaduwa for sale,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),3.500000e+08,4,4,600,Semi-Furnished,Vip
4,4bdrm Duplex in Gbagada Lagos for sale,"Gbagada, Oworonshoki / Gbagada",Oworonshoki / Gbagada,Gbagada,3.000000e+08,4,5,150,Semi-Furnished,Enterprise

In [52]:
new_df['Is_Boost'] = new_df['Is_Boost'].replace('Vip', 'VIP')
new_df.head()

,Title,Region,Region_Name,Region_Parent_Name,Price,Bedrooms,Bathrooms,Property_Size,Furnishing,Is_Boost
0,2bdrm Apartment in Lekki Phase 1 for sale,"Lekki, Lekki Phase 1",Lekki Phase 1,Lekki,3.500000e+08,2,3,150,Semi-Furnished,Enterprise
1,5bdrm Duplex in Wuse 2 for sale,"Abuja (FCT), Wuse 2",Wuse 2,Abuja (FCT),1.300000e+09,5,6,1200,Unfurnished,Diamond
2,4bdrm Duplex in Sangotedo for sale,"Ajah, Sangotedo",Sangotedo,Ajah,1.800000e+08,4,4,300,Unfurnished,Enterprise
3,4bdrm Duplex in Gaduwa for sale,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),3.500000e+08,4,4,600,Semi-Furnished,VIP
4,4bdrm Duplex in Gbagada Lagos for sale,"Gbagada, Oworonshoki / Gbagada",Oworonshoki / Gbagada,Gbagada,3.000000e+08,4,5,150,Semi-Furnished,Enterprise

In [22]:
total_duplicates = new_df.duplicated().sum()
print(total_duplicates)

0

In [24]:

new_df.to_csv('data/jiji_housing_cleaned.csv', index=False)
new_df.info()

<class 'pandas.DataFrame'>
Index: 19 entries, 0 to 19
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               19 non-null     str
 1   Region              19 non-null     str
 2   Region_Name         19 non-null     str
 3   Region_Parent_Name  19 non-null     str
 4   Price               19 non-null     float64
 5   Bedrooms            19 non-null     int64
 6   Bathrooms           19 non-null     int64
 7   Property_Size       19 non-null     int64
 8   Furnishing          19 non-null     str
 9   Is_Boost            19 non-null     str
dtypes: float64(1), int64(3), str(6)
memory usage: 3.3 KB

In [26]:
#Exploratory Data Analysis (EDA)

In [34]:

average_price = round(new_df['Price'].mean(), 2)
print('Housing Average Price(#)', average_price)

Housing Average Price(#) 702473684.21

In [35]:

round(new_df.groupby('Region')['Price'].mean(), 2)

Region
Abuja (FCT), Gaduwa               3.500000e+08
Abuja (FCT), Galadimawa           5.500000e+08
Abuja (FCT), Wuse 2               1.300000e+09
Ajah, Sangotedo                   1.800000e+08
Alimosho, Egbeda                  5.000000e+08
Delta State, Ethiope West         1.200000e+07
Gbagada, Oworonshoki / Gbagada    3.000000e+08
Ibadan, Akobo                     2.850000e+08
Ibadan, Bodija                    3.250000e+08
Ikeja, Ikeja GRA                  2.500000e+09
Ikeja, Opebi                      5.500000e+08
Lekki, Chevron                    3.000000e+08
Lekki, Ikate                      1.200000e+09
Lekki, Lekki Phase 1              3.500000e+08
Lekki, Osapa london               1.700000e+09
Oshodi, Airport Road / Oshodi     2.600000e+08
Name: Price, dtype: float64

In [38]:
property_counts = new_df['Property_Size'].value_counts().sort_values(ascending=False).head(20).reset_index(name='Count')
print(property_counts)

   Property_Size  Count
0           1000      5
1            300      4
2            150      2
3           1200      2
4            600      1
5            400      1
6            500      1
7             30      1
8            450      1
9            280      1

In [40]:
region_counts = new_df['Region'].value_counts().sort_values(ascending=False).head(20).reset_index(name='Count')
print(region_counts)

                            Region  Count
0                     Lekki, Ikate      3
1                    Ibadan, Akobo      2
2             Lekki, Lekki Phase 1      1
3              Abuja (FCT), Wuse 2      1
4                  Ajah, Sangotedo      1
5              Abuja (FCT), Gaduwa      1
6   Gbagada, Oworonshoki / Gbagada      1
7                     Ikeja, Opebi      1
8                 Alimosho, Egbeda      1
9              Lekki, Osapa london      1
10   Oshodi, Airport Road / Oshodi      1
11       Delta State, Ethiope West      1
12                  Ibadan, Bodija      1
13                Ikeja, Ikeja GRA      1
14                  Lekki, Chevron      1
15         Abuja (FCT), Galadimawa      1

In [53]:
new_df.groupby('Region')['Price'].mean().round(2).sort_values(ascending=False).reset_index(name='Price')

                            Region         Price
0                 Ikeja, Ikeja GRA  2.500000e+09
1              Lekki, Osapa london  1.700000e+09
2              Abuja (FCT), Wuse 2  1.300000e+09
3                     Lekki, Ikate  1.200000e+09
4                     Ikeja, Opebi  5.500000e+08
5          Abuja (FCT), Galadimawa  5.500000e+08
6                 Alimosho, Egbeda  5.000000e+08
7              Abuja (FCT), Gaduwa  3.500000e+08
8             Lekki, Lekki Phase 1  3.500000e+08
9                   Ibadan, Bodija  3.250000e+08
10                  Lekki, Chevron  3.000000e+08
11  Gbagada, Oworonshoki / Gbagada  3.000000e+08
12                   Ibadan, Akobo  2.850000e+08
13   Oshodi, Airport Road / Oshodi  2.600000e+08
14                 Ajah, Sangotedo  1.800000e+08
15       Delta State, Ethiope West  1.200000e+07

In [61]:
#Which regions dominate premium property sales?
vip_df = new_df[new_df['Is_Boost'] == 'VIP']

region_totals = vip_df['Region'].value_counts()

print(region_totals)

Region
Abuja (FCT), Gaduwa    1
Name: count, dtype: int64

In [65]:
#Are furnished apartments more expensive on average?

furnished = new_df.groupby('Furnishing')['Price'].mean().sort_values(ascending=False).head(20).reset_index(name='Average')
print(furnished)

       Furnishing       Average
0     Unfurnished  9.668889e+08
1  Semi-Furnished  5.333333e+08
2       Furnished  3.612500e+08

In [67]:
#Do boosted/enterprise listings have higher prices?

boosted = new_df.groupby('Is_Boost')['Price'].sum().sort_values(ascending=False).head(20).reset_index(name='Total Price')
print(boosted)

     Is_Boost   Total Price
0  Enterprise  1.168500e+10
1     Diamond  1.300000e+09
2         VIP  3.500000e+08
3       False  1.200000e+07